---

- hosts: "db1"
  become: True
  become_user: root

  tasks:

  - name: "Starting Master"
    systemd:
      name: mysql
      enabled: yes
      state: restarted

  - name: "Setting Master Write Enabled"
    mysql_variables:
      variable: read_only
      value: 0

  - name: "Resetting Replication If Necessary"
    mysql_replication:
      mode: resetslaveall

  - name: "Removing Unnecessary Users"
    command: mysql -e "SET SESSION binlog_format = 'STATEMENT'; DELETE FROM `mysql`.`user` WHERE `host` IN ('node1','node2');";

  - name: "Removing 'test' Database"
    mysql_db:
      name: test
      state: absent

  - name: "Removing ''@'localhost'"
    mysql_user:
      name: ''
      host: 'localhost'
      state: absent

  - name: "Removing 'root'@'::1'"
    mysql_user:
      name: root
      host: "::1"
      state: absent

  - name: "Adding '{{ maxscale_user }}'@'10.%'"
    mysql_user:
      name: '{{ maxscale_user }}'
      host: '10.%'
      password: "{{ maxscale_pass }}"
      update_password: on_create
      priv: '*.*:SUPER,RELOAD,REPLICATION CLIENT,REPLICATION SLAVE,SHOW DATABASES/mysql.db:SELECT/mysql.user:SELECT/mysql.roles_mapping:SELECT/mysql.tables_priv:SELECT/maxscale_schema.*:CREATE,INSERT,UPDATE,DELETE,SELECT'
      state: present

  - name: "Adding SST User"
    mysql_user:
      name: "{{ sst_user }}"
      password: "{{ sst_pass }}"
      host: "localhost"
      priv: '*.*:RELOAD,LOCK TABLES,REPLICATION CLIENT,CREATE TABLESPACE,PROCESS,SUPER,CREATE,INSERT,SELECT'
      state: present

  - name: "Adding '{{ dba_user }}'@'localhost'"
    mysql_user:
      name: '{{ dba_user }}'
      host: 'localhost'
      password: '{{ dba_pass }}'
      update_password: on_create
      priv: '*.*:ALL,GRANT'
      state: present

  - name: "Adding '{{ dba_user }}'@'127.0.0.1'"
    mysql_user:
      name: '{{ dba_user }}'
      host: '127.0.0.1'
      password: '{{ dba_pass }}'
      update_password: on_create
      priv: '*.*:ALL,GRANT'
      state: present

  - name: "Adding '{{ dba_user }}'@'10.%'"
    mysql_user:
      name: '{{ dba_user }}'
      host: '10.%'
      password: '{{ dba_pass }}'
      update_password: on_create
      priv: '*.*:ALL,GRANT'
      state: present

  - name: "Adding '{{ repli_user }}'@'10.%'"
    mysql_user:
      name: '{{ repli_user }}'
      host: '10.%'
      password: '{{ repli_pass }}'
      update_password: on_create
      priv: '*.*:REPLICATION CLIENT,REPLICATION SLAVE'
      state: present

  - name: "Adding '{{ repli_user }}'@'localhost'"
    mysql_user:
      name: '{{ repli_user }}'
      host: 'localhost'
      password: '{{ repli_pass }}'
      update_password: on_create
      priv: '*.*:REPLICATION CLIENT,REPLICATION SLAVE'
      state: present

- hosts: "db2"
  become: True
  become_user: root

  tasks:

  - name: "Starting Slave"
    systemd:
      name: mysql
      enabled: yes
      state: restarted

  - name: "Setting Slave Read Only"
    mysql_variables:
      variable: read_only
      value: 1

  - name: "Stopping Slave"
    mysql_replication:
     mode: stopslave

  - name: "Setting Master Info"
    mysql_replication:
      mode: changemaster
      master_host: '{{ hostvars.db1.ansible_host }}'
      master_user: '{{ repli_user }}'
      master_password: '{{ repli_pass }}'

  - name: "Converting to MariaDB GTID"
    command: mysql -e "CHANGE MASTER TO master_use_gtid=slave_pos";

  - name: "Starting Slave"
    mysql_replication:
     mode: startslave
